import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0e1510",
        "outline": "#8e928d",
        "surface-variant": "#2f3731",
        "tertiary-container": "#012024",
        "on-tertiary-fixed-variant": "#2f4b4f",
        "surface": "#0e1510",
        "on-error": "#690005",
        "on-background": "#dde5dc",
        "on-secondary-fixed": "#241918",
        "on-surface-variant": "#c4c7c2",
        "error-container": "#93000a",
        "tertiary-fixed": "#c9e8ed",
        "on-primary-fixed-variant": "#3c4a47",
        "surface-tint": "#bbcac6",
        "secondary-container": "#524342",
        "surface-container-low": "#161d18",
        "surface-container-high": "#242c26",
        "on-secondary": "#3a2d2c",
        "outline-variant": "#444844",
        "on-tertiary-container": "#6c898e",
        "primary-container": "#121f1c",
        "on-secondary-container": "#c4b1af",
        "secondary": "#d6c2c0",
        "error": "#ffb4ab",
        "inverse-on-surface": "#2b322d",
        "secondary-fixed-dim": "#d6c2c0",
        "secondary-fixed": "#f3dedb",
        "on-tertiary": "#183539",
        "on-tertiary-fixed": "#001f23",
        "primary-fixed-dim": "#bbcac6",
        "on-primary-fixed": "#111e1c",
        "on-primary": "#263330",
        "background": "#0e1510",
        "surface-container": "#1a211c",
        "on-surface": "#dde5dc",
        "on-secondary-fixed-variant": "#524342",
        "tertiary": "#aeccd1",
        "on-primary-container": "#798884",
        "surface-container-lowest": "#09100b",
        "inverse-primary": "#53615e",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dde5dc",
        "surface-container-highest": "#2f3731",
        "surface-bright": "#343b35",
        "primary": "#bbcac6",
        "tertiary-fixed-dim": "#aeccd1",
        "primary-fixed": "#d7e6e2"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Anton", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
export default config
